extends: eslint:recommended
parserOptions:
  ecmaVersion: 2019
globals:
  Components:  readonly
  Cu:          readonly
  Cc:          readonly
  Ci:          readonly
  ChromeUtils: readonly
  pref:        readonly
rules:
  no-empty-pattern:
    - off
  semi:
    - error
    - always
